export default function robots() {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://www.mpcpct.com";
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/admin",
          "/api/",
          "/exam_mode",
          "/payment",
          "/payment-app",
          "/payment-success",
          "/payment-failed",
          "/dashboard",
          "/profile",
          "/login",
          "/signup",
          "/forget",
          "/verify-phone",
          "/videos",
          "/video/",
          "/doubts/",
          "/debug",
        ],
      },
      {
        userAgent: "Googlebot",
        allow: "/",
        disallow: [
          "/admin",
          "/api/",
          "/exam_mode",
          "/payment",
          "/payment-app",
          "/payment-success",
          "/payment-failed",
          "/dashboard",
          "/profile",
          "/login",
          "/signup",
          "/forget",
          "/verify-phone",
          "/videos",
          "/video/",
          "/doubts/",
          "/debug",
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  };
}
